### ISSUE TITLE
Building java-ui fails. Authorization?

### ISSUE THREAD

**Issue by FMNSSun** [p2abcengine/p2abcengine#4]
I can't build the java-ui.
```
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[INFO] Computing target platform for MavenProject: eu.abc4trust.ui:eu.abc4trust.ri.ui.user:1.1.0.qualifier @ /home/new/p2abcengine/Code/java-ui/eu.abc4trust.ri.ui.user/pom.xml
Downloading: https://abc4trust.miracleas.dk/nexus/content/groups/public/eu/abc4trust/ri/abc4trust-xml/1.1.13/abc4trust-xml-1.1.13.pom

Downloading: https://abc4trust.miracleas.dk/nexus/content/groups/public/eu/abc4trust/ri/abce-interfaces/1.1.13/abce-interfaces-1.1.13.pom

Downloading: https://abc4trust.miracleas.dk/nexus/content/groups/public/eu/abc4trust/ri/ui-osgi-dependencies/1.1.13/ui-osgi-dependencies-1.1.13.pom

[ERROR] Internal error: java.lang.RuntimeException: Could not resolve project dependencies: Unable to get dependency information for eu.abc4trust.ri:abc4trust-xml:jar:1.1.13: Failed to retrieve POM for eu.abc4trust.ri:abc4trust-xml:jar:1.1.13: Could not transfer artifact eu.abc4trust.ri:abc4trust-xml:pom:1.1.13 from/to maven.abc4trust.miracleas.dk (https://abc4trust.miracleas.dk/nexus/content/groups/public/): Not authorized, ReasonPhrase:Authorization Required.
[ERROR] eu.abc4trust.ri:abc4trust-xml:jar:1.1.13
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] eclipse-juno (http://download.eclipse.org/releases/juno, releases=false, snapshots=false),
[ERROR] maven.abc4trust.miracleas.dk (https://abc4trust.miracleas.dk/nexus/content/groups/public/, releases=true, snapshots=true),
[ERROR] central (http://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] Path to dependency:
[ERROR] 1) eu.abc4trust.ui:eu.abc4trust.ri.ui.user:pom:1.1.0.qualifier
[ERROR] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve project dependencies
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.RuntimeException: Could not resolve project dependencies
	at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.addPomDependenciesToTargetPlatform(P2TargetPlatformResolver.java:292)
	at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.computeTargetPlatform(P2TargetPlatformResolver.java:199)
	at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:94)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:82)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	... 11 more
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for eu.abc4trust.ri:abc4trust-xml:jar:1.1.13: Failed to retrieve POM for eu.abc4trust.ri:abc4trust-xml:jar:1.1.13: Could not transfer artifact eu.abc4trust.ri:abc4trust-xml:pom:1.1.13 from/to maven.abc4trust.miracleas.dk (https://abc4trust.miracleas.dk/nexus/content/groups/public/): Not authorized, ReasonPhrase:Authorization Required.
  eu.abc4trust.ri:abc4trust-xml:jar:1.1.13

from the specified remote repositories:
  eclipse-juno (http://download.eclipse.org/releases/juno, releases=false, snapshots=false),
  maven.abc4trust.miracleas.dk (https://abc4trust.miracleas.dk/nexus/content/groups/public/, releases=true, snapshots=true),
  central (http://repo.maven.apache.org/maven2, releases=true, snapshots=false)
Path to dependency: 
	1) eu.abc4trust.ui:eu.abc4trust.ri.ui.user:pom:1.1.0.qualifier


	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:576)
	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(DefaultLegacyArtifactCollector.java:144)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:464)
	at org.apache.maven.repository.legacy.LegacyRepositorySystem.resolve(LegacyRepositorySystem.java:352)
	at org.apache.maven.DefaultProjectDependenciesResolver.resolveImpl(DefaultProjectDependenciesResolver.java:158)
	at org.apache.maven.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:75)
	at org.apache.maven.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:59)
	at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.addPomDependenciesToTargetPlatform(P2TargetPlatformResolver.java:273)
	... 16 more
Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Failed to retrieve POM for eu.abc4trust.ri:abc4trust-xml:jar:1.1.13: Could not transfer artifact eu.abc4trust.ri:abc4trust-xml:pom:1.1.13 from/to maven.abc4trust.miracleas.dk (https://abc4trust.miracleas.dk/nexus/content/groups/public/): Not authorized, ReasonPhrase:Authorization Required.
	at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:600)
	at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:192)
	at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:532)
	... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact eu.abc4trust.ri:abc4trust-xml:pom:1.1.13 from/to maven.abc4trust.miracleas.dk (https://abc4trust.miracleas.dk/nexus/content/groups/public/): Not authorized, ReasonPhrase:Authorization Required.
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:285)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:267)
	at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:579)
	... 25 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact eu.abc4trust.ri:abc4trust-xml:pom:1.1.13 from/to maven.abc4trust.miracleas.dk (https://abc4trust.miracleas.dk/nexus/content/groups/public/): Not authorized, ReasonPhrase:Authorization Required.
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized, ReasonPhrase:Authorization Required.
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:839)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
	... 4 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

Judging by the Log I'm not Authorized to do so.

**Comment by MichaelStausholm** [comment]
The new 1.1.36 version of the ui should fix this issue.
